backend:
  name: test-repo

locale: es

# --- Lo que faltaba para que no de error ---
media_folder: "public/uploads"
public_folder: "/uploads"

media_library:
  name: "uploadcare" # Aunque no lo uses, el schema pide definirlo
  config:
    publicKey: "demopublickey" 
# ------------------------------------------

collections:
  - name: "prueba"
    label: "Prueba"
    folder: "src/content/prueba"
    create: true
    fields:
      - {label: "Título", name: "titulo", widget: "string"}