backend:
  name: git-gateway
  branch: main # Asegurate de que sea tu rama principal

locale: es

# Carpetas donde se guardarán las imágenes
media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "prueba"
    label: "Prueba"
    folder: "src/content/prueba"
    create: true
    fields:
      - {label: "Título", name: "titulo", widget: "string"}